plugins:
  - jekyll-remote-theme

remote_theme: daattali/beautiful-jekyll

title: Nadine Bock
description: "Angehende Fachinformatikerin für Systemintegration"

author: Nadine Bock

url: "https://nadinebock.github.io"
